update ssn validation (Safari 16.3 & prior compatibility)
episphere/quest pull request #433
Opened 2024-03-12 21:11 UTC by JoeArmani

Update validation.js SSN handling for Safari 16.3 and prior compatibility.

@danielruss @anthonypetersen Please advise on this when you can.

**Existing RegExp rules:**
(1) Does not start with ‘9’, ‘000’, or ‘666’.
(2) Capture two more digits. Ensure they don’t match the first digit.
(3) optional dash (‘-‘)
(4) Ensure middle two are digits. Cannot be ’00’
(5) Optional dash.
(6) Ensure last four are digits. Cannot be ‘0000’
(7) Ensure it isn’t a single number repeated throughout.

**Problem:**
This part has support issues ‘negative lookbehind,’ unsupported in Safari 16.3 and prior. Based on DataDog logs, this is impacting several participants/week due to not updating their browsers.
Here's the unsupported part: (?<!\1{3}-?\1{2}-?\1{4}?) causing a syntax error (the Quest import fails).

**Error Traced back to the validate function:** 
Note: This works in Chrome, Firefox, and Safari versions 16.4+, it was unsupported through Safari v16.3 -- we appear to have many participants using Safari versions as far back as 15.6 from the data I've seen. In unsupported versions, the lookbehind creates a syntax error and the Quest import fails.
<img width="1297" alt="Screenshot 2024-03-12 at 5 04 16 PM" src="https://github.com/episphere/quest/assets/93854858/2f022be9-6a90-4931-ae09-ed4a9ff773e7">

 
**Browser support chart:**
https://caniuse.com/?search=RegExp%20lookbehind%20assertions

**Updated handling:**
(1) Handle all steps above except 7.

•Clean dashes at specific locations for simplified checking of all conditions. Do not clean further (that would be too permissive).
const normalizedSSN = inputElement.value.replace(/^(\d{3})-?(\d{2})-?(\d{4})$/, '$1$2$3');

•Use Daniel’s formatting check, adapted to the normalizedSSN
!/^(?!9|000|666)[0-8]\d{2}(?!00)\d{2}(?!0000)\d{4}$/.test(normalizedSSN)

(2) Handle & adapt step 7 from existing rules to match Connect PWA and cloud function validation. 
•Integrate Daniel and Tony’s rules for SSNs "078051120", "219099999", "111111111", and “333333333"
•Omit handling of repeating numbers 2, 4, 5, 6, 7, 8 to match validation in PWA and SSN cloud function

2024-03-12 22:09 UTC, danielruss commented
The regex does not prevent 111-11-1111 (as 11111111). Can you try /^(?!9|000|666)(\d)(?!\1{2}-?\1{2}-?\1{4})\d{2}-?(?!00)\d{2}-?(?!0000)\d{4}/mg

https://regex101.com/r/YD2Exm/1

2024-03-12 22:15 UTC, danielruss requested changes
Sorry, I placed the review in the wrong place..

The regex does not prevent 111-11-1111 (as 11111111). Can you try /^(?!9|000|666)(\d)(?!\1{2}-?\1{2}-?\1{4})\d{2}-?(?!00)\d{2}-?(?!0000)\d{4}/mg

https://regex101.com/r/YD2Exm/1

My change is to convert the negative lookbehind to a negative lookahead. After the first digit (x) (capture group), you cannot have xx-xx-xxxx

2024-03-13 16:17 UTC, JoeArmani commented
> https://regex101.com/r/YD2Exm/1

Thanks @danielruss. Good news: This updated version does appear to work with older versions of Safari.

https://github.com/episphere/quest/assets/93854858/9f7abfa0-92ef-4ffe-96ee-a444441e4bb4



Two questions:

(1) The only remaining discrepancy is that this invalidates all fully repeating numbers [0-9]. The PWA & cloud function code allows all 2s, 4s, 5s, 6s, 7s, 8s to pass (invalidating 1s, 3s, and 9s).

(2) If I update to your new regex, I'm assuming I should update my submitted line 194 below that handles 1s and 3s (please confirm):
previously submitted: `["078051120","219099999","111111111","333333333"].includes(normalizedSSN)`
would update to: `["078051120","219099999"].includes(normalizedSSN)`

Please let me know your preference here, and I'll wrap this up. Thanks.

For reference, here's the validation in the PWA. The same validation is used in the new cloud function (not yet deployed to prod):
https://github.com/episphere/connectApp/blob/c157f2fc62ffd01e6e0dbecc5cb159d2818058e6/js/pages/ssn.js#L500

2024-03-13 19:58 UTC, danielruss commented
@JoeArmani  Sorry, I did not know that 222-22-2222 was a valid SSN.  I updated the regex to disallow all 1's and all 3's (all 9 is still disallowed because cant start with 9, and all zeros are disallowed because you cant start with 000.

2024-03-14 20:09 UTC, JoeArmani commented
@danielruss Thanks. I didn't know either. I think that was Mia and Tony's conclusion.

Sorry, I'm missing something in communication here. Can you post the version you updated? I think I still see the previous version when I follow the link.

2024-03-15 14:31 UTC, danielruss commented
Hi Joe! Sorry, I updated the link, but it appears that even though I saved it.  Regex 101 takes you back to the original.  Anyway, I [remade the RegEx pattern](https://regex101.com/r/5dAgDX/1) and it includes the two "bad" patterns.

2024-03-15 16:53 UTC, danielruss approved these changes
Please make sure you "Squash" the commits.  Otherwise looks good

2024-03-15 16:54 UTC, JoeArmani commented
@danielruss That's great. Thanks for the regex lesson.
I'll need to learn more about some of these addon regex features. They're more powerful than I realized.
•Tested and working in the iOS 16.1 simulator (Safari 16.1).
•Passing local JS tests: https://gist.github.com/JoeArmani/5faf340a793f634a4d51c602bb9572a1

I removed the regularization and .includes since your regex covers those cases.

2024-03-15 16:56 UTC, danielruss commented
Thank you for putting together the PR!

2024-03-15 17:15 UTC, merged