handle checkbox (multi-selection) grid CSS and logic
episphere/quest pull request #442
Opened 2024-06-06 17:33 UTC by JoeArmani

Handle case I missed: multi-selection grid with checkbox.
•Updated CSS in ActiveLogic.css and Default.css
•Added input type checkbox to grid response handlers

Restrict refreshListeners (accessibility listeners) when moduleParams.renderObj.activate is falsy (when using renderer). This should prevent it from falsely applying focus in the renderer's markup tool.

2024-06-06 17:52 UTC, danielruss requested changes
Please rebase your code.  
`git rebase main`

2024-06-06 18:06 UTC, JoeArmani commented
@danielruss thanks for reviewing. I rebased

2024-06-06 18:07 UTC, anthonypetersen approved these changes

2024-06-07 12:36 UTC, anthonypetersen commented
@danielruss are you fine with these changes now? we have a bunch of prod tickets that are popping up and we need to get a fix in

2024-06-07 13:19 UTC, merged